services:
  - type: web
    name: scripturecast
    runtime: python
    buildCommand: ./start.sh
    startCommand: python run.py
    envVars:
      - key: PORT
        value: 8000
      - key: ASSEMBLYAI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
